
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Apr 15 2026 10:15:02 IST (Apr 15 2026 04:45:02 UTC)

// Verification Directory fv/hybrid_dram_ecc_top 

module hybrid_dram_ecc_top(clk, rst_n, cpu_data_in, write_en, read_en,
     dram_bus_write, dram_bus_read, cpu_data_out, data_ready,
     error_uncorrectable);
  input clk, rst_n, write_en, read_en;
  input [63:0] cpu_data_in;
  input [159:0] dram_bus_read;
  output [159:0] dram_bus_write;
  output [63:0] cpu_data_out;
  output data_ready, error_uncorrectable;
  wire clk, rst_n, write_en, read_en;
  wire [63:0] cpu_data_in;
  wire [159:0] dram_bus_read;
  wire [159:0] dram_bus_write;
  wire [63:0] cpu_data_out;
  wire data_ready, error_uncorrectable;
  wire [63:0] bch_corrected_data;
  wire [2:0] bch_fixer_state;
  wire bch_done, n_4, n_15, n_22, n_23, n_24, n_25, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_35, n_38, n_41;
  wire n_44, n_46, n_48, n_50, n_52, n_53, n_55, n_57;
  wire n_59, n_61, n_63, n_65, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_144, n_145;
  wire n_146, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180, n_181, n_182, n_183, n_184, n_185, n_186;
  wire n_187, n_188, n_189, n_190, n_191, n_192, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_205, n_208, n_209, n_210, n_211, n_212, n_213, n_214;
  wire n_215, n_216, n_217, n_218, n_219, n_220, n_221, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_233, n_234, n_235, n_236, n_237, n_238;
  wire n_239, n_240, n_241, n_242, n_243, n_244, n_245, n_246;
  wire n_247, n_248, n_249, n_250, n_252, n_253, n_254, n_263;
  wire n_265, n_267, n_268, n_269, n_270, n_271, n_272, n_273;
  wire n_274, n_275, n_276, n_277, n_278, n_279, n_280, n_281;
  wire n_504, n_505, n_506, n_507, n_508, n_509, n_510, n_511;
  wire n_512, n_513, n_514, n_515, n_516, n_517, n_518, n_519;
  wire n_520, n_521, n_522, n_523, n_524, n_525;
  assign error_uncorrectable = 1'b0;
  assign dram_bus_write[20] = dram_bus_write[92];
  assign dram_bus_write[21] = dram_bus_write[93];
  assign dram_bus_write[22] = dram_bus_write[94];
  assign dram_bus_write[23] = dram_bus_write[95];
  assign dram_bus_write[24] = dram_bus_write[88];
  assign dram_bus_write[25] = dram_bus_write[89];
  assign dram_bus_write[26] = dram_bus_write[90];
  assign dram_bus_write[27] = dram_bus_write[91];
  assign dram_bus_write[28] = dram_bus_write[92];
  assign dram_bus_write[29] = dram_bus_write[93];
  assign dram_bus_write[30] = dram_bus_write[94];
  assign dram_bus_write[31] = dram_bus_write[95];
  assign dram_bus_write[32] = dram_bus_write[88];
  assign dram_bus_write[33] = dram_bus_write[89];
  assign dram_bus_write[34] = dram_bus_write[90];
  assign dram_bus_write[35] = dram_bus_write[91];
  assign dram_bus_write[36] = dram_bus_write[92];
  assign dram_bus_write[37] = dram_bus_write[93];
  assign dram_bus_write[38] = dram_bus_write[94];
  assign dram_bus_write[39] = dram_bus_write[95];
  assign dram_bus_write[40] = dram_bus_write[88];
  assign dram_bus_write[41] = dram_bus_write[89];
  assign dram_bus_write[42] = dram_bus_write[90];
  assign dram_bus_write[43] = dram_bus_write[91];
  assign dram_bus_write[44] = dram_bus_write[92];
  assign dram_bus_write[45] = dram_bus_write[93];
  assign dram_bus_write[46] = dram_bus_write[94];
  assign dram_bus_write[47] = dram_bus_write[95];
  assign dram_bus_write[48] = dram_bus_write[88];
  assign dram_bus_write[49] = dram_bus_write[89];
  assign dram_bus_write[50] = dram_bus_write[90];
  assign dram_bus_write[51] = dram_bus_write[91];
  assign dram_bus_write[52] = dram_bus_write[92];
  assign dram_bus_write[53] = dram_bus_write[93];
  assign dram_bus_write[54] = dram_bus_write[94];
  assign dram_bus_write[55] = dram_bus_write[95];
  assign dram_bus_write[56] = dram_bus_write[88];
  assign dram_bus_write[57] = dram_bus_write[89];
  assign dram_bus_write[58] = dram_bus_write[90];
  assign dram_bus_write[59] = dram_bus_write[91];
  assign dram_bus_write[60] = dram_bus_write[92];
  assign dram_bus_write[61] = dram_bus_write[93];
  assign dram_bus_write[62] = dram_bus_write[94];
  assign dram_bus_write[63] = dram_bus_write[95];
  assign dram_bus_write[64] = dram_bus_write[88];
  assign dram_bus_write[65] = dram_bus_write[89];
  assign dram_bus_write[66] = dram_bus_write[90];
  assign dram_bus_write[67] = dram_bus_write[91];
  assign dram_bus_write[68] = dram_bus_write[92];
  assign dram_bus_write[69] = dram_bus_write[93];
  assign dram_bus_write[70] = dram_bus_write[94];
  assign dram_bus_write[71] = dram_bus_write[95];
  assign dram_bus_write[72] = dram_bus_write[88];
  assign dram_bus_write[73] = dram_bus_write[89];
  assign dram_bus_write[74] = dram_bus_write[90];
  assign dram_bus_write[75] = dram_bus_write[91];
  assign dram_bus_write[76] = dram_bus_write[92];
  assign dram_bus_write[77] = dram_bus_write[93];
  assign dram_bus_write[78] = dram_bus_write[94];
  assign dram_bus_write[79] = dram_bus_write[95];
  assign dram_bus_write[80] = dram_bus_write[88];
  assign dram_bus_write[81] = dram_bus_write[89];
  assign dram_bus_write[82] = dram_bus_write[90];
  assign dram_bus_write[83] = dram_bus_write[91];
  assign dram_bus_write[84] = dram_bus_write[92];
  assign dram_bus_write[85] = dram_bus_write[93];
  assign dram_bus_write[86] = dram_bus_write[94];
  assign dram_bus_write[87] = dram_bus_write[95];
  assign dram_bus_write[96] = cpu_data_in[0];
  assign dram_bus_write[97] = cpu_data_in[1];
  assign dram_bus_write[98] = cpu_data_in[2];
  assign dram_bus_write[99] = cpu_data_in[3];
  assign dram_bus_write[100] = cpu_data_in[4];
  assign dram_bus_write[101] = cpu_data_in[5];
  assign dram_bus_write[102] = cpu_data_in[6];
  assign dram_bus_write[103] = cpu_data_in[7];
  assign dram_bus_write[104] = cpu_data_in[8];
  assign dram_bus_write[105] = cpu_data_in[9];
  assign dram_bus_write[106] = cpu_data_in[10];
  assign dram_bus_write[107] = cpu_data_in[11];
  assign dram_bus_write[108] = cpu_data_in[12];
  assign dram_bus_write[109] = cpu_data_in[13];
  assign dram_bus_write[110] = cpu_data_in[14];
  assign dram_bus_write[111] = cpu_data_in[15];
  assign dram_bus_write[112] = cpu_data_in[16];
  assign dram_bus_write[113] = cpu_data_in[17];
  assign dram_bus_write[114] = cpu_data_in[18];
  assign dram_bus_write[115] = cpu_data_in[19];
  assign dram_bus_write[116] = cpu_data_in[20];
  assign dram_bus_write[117] = cpu_data_in[21];
  assign dram_bus_write[118] = cpu_data_in[22];
  assign dram_bus_write[119] = cpu_data_in[23];
  assign dram_bus_write[120] = cpu_data_in[24];
  assign dram_bus_write[121] = cpu_data_in[25];
  assign dram_bus_write[122] = cpu_data_in[26];
  assign dram_bus_write[123] = cpu_data_in[27];
  assign dram_bus_write[124] = cpu_data_in[28];
  assign dram_bus_write[125] = cpu_data_in[29];
  assign dram_bus_write[126] = cpu_data_in[30];
  assign dram_bus_write[127] = cpu_data_in[31];
  assign dram_bus_write[128] = cpu_data_in[32];
  assign dram_bus_write[129] = cpu_data_in[33];
  assign dram_bus_write[130] = cpu_data_in[34];
  assign dram_bus_write[131] = cpu_data_in[35];
  assign dram_bus_write[132] = cpu_data_in[36];
  assign dram_bus_write[133] = cpu_data_in[37];
  assign dram_bus_write[134] = cpu_data_in[38];
  assign dram_bus_write[135] = cpu_data_in[39];
  assign dram_bus_write[136] = cpu_data_in[40];
  assign dram_bus_write[137] = cpu_data_in[41];
  assign dram_bus_write[138] = cpu_data_in[42];
  assign dram_bus_write[139] = cpu_data_in[43];
  assign dram_bus_write[140] = cpu_data_in[44];
  assign dram_bus_write[141] = cpu_data_in[45];
  assign dram_bus_write[142] = cpu_data_in[46];
  assign dram_bus_write[143] = cpu_data_in[47];
  assign dram_bus_write[144] = cpu_data_in[48];
  assign dram_bus_write[145] = cpu_data_in[49];
  assign dram_bus_write[146] = cpu_data_in[50];
  assign dram_bus_write[147] = cpu_data_in[51];
  assign dram_bus_write[148] = cpu_data_in[52];
  assign dram_bus_write[149] = cpu_data_in[53];
  assign dram_bus_write[150] = cpu_data_in[54];
  assign dram_bus_write[151] = cpu_data_in[55];
  assign dram_bus_write[152] = cpu_data_in[56];
  assign dram_bus_write[153] = cpu_data_in[57];
  assign dram_bus_write[154] = cpu_data_in[58];
  assign dram_bus_write[155] = cpu_data_in[59];
  assign dram_bus_write[156] = cpu_data_in[60];
  assign dram_bus_write[157] = cpu_data_in[61];
  assign dram_bus_write[158] = cpu_data_in[62];
  assign dram_bus_write[159] = cpu_data_in[63];
  OAI21X1 g14947__2398(.A0 (n_276), .A1 (n_277), .B0 (n_278), .Y
       (dram_bus_write[15]));
  OAI21X1 g14950__5107(.A0 (n_274), .A1 (n_273), .B0 (n_275), .Y
       (dram_bus_write[14]));
  OAI21X1 g14951__6260(.A0 (n_268), .A1 (n_267), .B0 (n_269), .Y
       (dram_bus_write[10]));
  OAI21X1 g14952__4319(.A0 (n_271), .A1 (n_270), .B0 (n_272), .Y
       (dram_bus_write[8]));
  OAI21X1 g14949__8428(.A0 (n_280), .A1 (n_279), .B0 (n_281), .Y
       (dram_bus_write[0]));
  OAI21X1 g14948__5526(.A0 (n_505), .A1 (n_263), .B0 (n_265), .Y
       (dram_bus_write[2]));
  NAND2XL g14954__6783(.A (n_280), .B (n_279), .Y (n_281));
  NAND2XL g14957__3680(.A (n_277), .B (n_276), .Y (n_278));
  NAND2XL g14955__1617(.A (n_274), .B (n_273), .Y (n_275));
  NAND2XL g14958__2802(.A (n_271), .B (n_270), .Y (n_272));
  NAND2XL g14956__1705(.A (n_268), .B (n_267), .Y (n_269));
  OAI21X1 g14976__5122(.A0 (n_249), .A1 (n_248), .B0 (n_250), .Y
       (dram_bus_write[13]));
  NAND2XL g14953__8246(.A (n_505), .B (n_263), .Y (n_265));
  OAI21X1 g14959__7098(.A0 (n_245), .A1 (n_244), .B0 (n_246), .Y
       (dram_bus_write[3]));
  OAI21X1 g14975__6131(.A0 (n_225), .A1 (n_224), .B0 (n_226), .Y
       (dram_bus_write[11]));
  OAI21X1 g14972__1881(.A0 (n_242), .A1 (n_241), .B0 (n_243), .Y
       (dram_bus_write[9]));
  OAI21X1 g14974__5115(.A0 (n_216), .A1 (n_215), .B0 (n_217), .Y
       (dram_bus_write[6]));
  OAI21X1 g14970__7482(.A0 (n_230), .A1 (n_229), .B0 (n_231), .Y
       (dram_bus_write[5]));
  OAI21X1 g14973__4733(.A0 (n_219), .A1 (n_218), .B0 (n_220), .Y
       (dram_bus_write[7]));
  OAI21X1 g14961__6161(.A0 (n_239), .A1 (n_238), .B0 (n_240), .Y
       (dram_bus_write[16]));
  OAI21X1 g14960__9315(.A0 (n_236), .A1 (n_235), .B0 (n_237), .Y
       (dram_bus_write[1]));
  AOI21X1 g14964__9945(.A0 (n_222), .A1 (n_221), .B0 (n_223), .Y
       (n_277));
  MXI2XL g14977__2883(.A (n_254), .B (n_253), .S0 (n_515), .Y (n_276));
  AOI21X1 g14962__2346(.A0 (n_233), .A1 (n_232), .B0 (n_234), .Y
       (n_279));
  AOI21XL g14978__1666(.A0 (n_213), .A1 (n_252), .B0 (n_214), .Y
       (n_267));
  AOI21X1 g14963__7410(.A0 (n_247), .A1 (n_227), .B0 (n_228), .Y
       (n_273));
  MXI2XL g14979__6417(.A (n_254), .B (n_253), .S0 (n_89), .Y (n_270));
  XNOR2X4 g14967__5477(.A (n_252), .B (n_162), .Y (dram_bus_write[88]));
  XNOR2X4 g14969__2398(.A (n_205), .B (n_111), .Y (dram_bus_write[93]));
  XNOR2X4 g14980__5107(.A (n_127), .B (n_254), .Y (dram_bus_write[95]));
  OAI21X1 g14971__6260(.A0 (n_209), .A1 (n_208), .B0 (n_210), .Y
       (dram_bus_write[12]));
  NAND2XL g14987__4319(.A (n_249), .B (n_248), .Y (n_250));
  AOI21X1 g14965__8428(.A0 (n_247), .A1 (n_211), .B0 (n_212), .Y
       (n_263));
  NAND2XL g14983__5526(.A (n_245), .B (n_244), .Y (n_246));
  NAND2XL g14982__6783(.A (n_242), .B (n_241), .Y (n_243));
  NAND2XL g14981__3680(.A (n_239), .B (n_238), .Y (n_240));
  NAND2XL g14985__1617(.A (n_236), .B (n_235), .Y (n_237));
  NOR2XL g14986__2802(.A (n_233), .B (n_232), .Y (n_234));
  XNOR2X4 g14968__1705(.A (n_192), .B (n_165), .Y (dram_bus_write[91]));
  NAND2XL g14995__5122(.A (n_230), .B (n_229), .Y (n_231));
  NOR2XL g14989__8246(.A (n_247), .B (n_227), .Y (n_228));
  NAND2XL g14991__7098(.A (n_225), .B (n_224), .Y (n_226));
  NOR2XL g14992__6131(.A (n_222), .B (n_221), .Y (n_223));
  NAND2XL g14993__1881(.A (n_219), .B (n_218), .Y (n_220));
  NAND2XL g14994__5115(.A (n_216), .B (n_215), .Y (n_217));
  NOR2XL g14988__7482(.A (n_213), .B (n_252), .Y (n_214));
  AOI21X1 g15000__4733(.A0 (n_194), .A1 (n_504), .B0 (n_195), .Y
       (n_248));
  XNOR2X4 g14966__6161(.A (n_168), .B (n_124), .Y (dram_bus_write[90]));
  NOR2XL g14984__9315(.A (n_247), .B (n_211), .Y (n_212));
  NAND2XL g14990__9945(.A (n_209), .B (n_208), .Y (n_210));
  CLKINVX1 g15011(.A (n_254), .Y (n_253));
  OAI21X1 g14996__2883(.A0 (n_181), .A1 (n_180), .B0 (n_182), .Y
       (dram_bus_write[18]));
  MX2X1 g15012__2346(.A (n_197), .B (n_249), .S0 (n_158), .Y
       (dram_bus_write[17]));
  MXI2XL g15023__1666(.A (n_203), .B (n_202), .S0 (n_93), .Y (n_205));
  OAI21X1 g14997__7410(.A0 (n_184), .A1 (n_183), .B0 (n_185), .Y
       (dram_bus_write[4]));
  OAI21X1 g15004__6417(.A0 (n_178), .A1 (n_213), .B0 (n_179), .Y
       (n_218));
  AOI21XL g15001__5477(.A0 (n_173), .A1 (n_172), .B0 (n_174), .Y
       (n_225));
  AOI21X1 g14999__2398(.A0 (n_170), .A1 (n_169), .B0 (n_171), .Y
       (n_241));
  MXI2XL g15025__5107(.A (n_242), .B (n_198), .S0 (n_201), .Y (n_252));
  MXI2XL g15026__6260(.A (n_203), .B (n_202), .S0 (n_201), .Y (n_254));
  MXI2XL g15022__4319(.A (n_200), .B (n_199), .S0 (n_196), .Y (n_227));
  MXI2XL g15006__8428(.A (n_200), .B (n_199), .S0 (n_160), .Y (n_229));
  MXI2XL g15013__5526(.A (n_203), .B (n_202), .S0 (n_92), .Y (n_235));
  MXI2XL g15014__6783(.A (n_242), .B (n_198), .S0 (n_149), .Y (n_238));
  MXI2XL g15015__3680(.A (n_200), .B (n_199), .S0 (n_110), .Y (n_221));
  MXI2XL g15019__1617(.A (n_249), .B (n_197), .S0 (n_196), .Y (n_215));
  MXI2XL g15020__2802(.A (n_203), .B (n_202), .S0 (n_159), .Y (n_232));
  MXI2XL g14998__1705(.A (n_249), .B (n_197), .S0 (n_188), .Y (n_244));
  AOI21XL g15005__5122(.A0 (n_176), .A1 (n_175), .B0 (n_177), .Y
       (n_216));
  NOR2XL g15027__8246(.A (n_194), .B (n_504), .Y (n_195));
  MXI2XL g15024__7098(.A (n_196), .B (n_145), .S0 (n_191), .Y (n_224));
  XNOR2X4 g15008__6131(.A (n_268), .B (n_164), .Y (dram_bus_write[89]));
  XNOR2X4 g15010__1881(.A (n_163), .B (n_100), .Y (dram_bus_write[94]));
  XNOR2X4 g15009__5115(.A (n_138), .B (n_161), .Y (dram_bus_write[92]));
  MXI2XL g15017__7482(.A (n_187), .B (n_186), .S0 (n_191), .Y (n_192));
  MXI2XL g15007__4733(.A (n_190), .B (n_189), .S0 (n_516), .Y (n_274));
  MXI2XL g15016__6161(.A (n_118), .B (n_119), .S0 (n_191), .Y (n_208));
  MXI2XL g15002__9315(.A (n_190), .B (n_189), .S0 (n_188), .Y (n_209));
  MXI2XL g15018__9945(.A (n_187), .B (n_186), .S0 (n_242), .Y (n_211));
  MXI2XL g15021__2883(.A (n_166), .B (n_167), .S0 (n_203), .Y (n_219));
  NAND2XL g15028__2346(.A (n_184), .B (n_183), .Y (n_185));
  NAND2XL g15029__1666(.A (n_181), .B (n_180), .Y (n_182));
  NAND2XL g15030__7410(.A (n_178), .B (n_213), .Y (n_179));
  NOR2XL g15033__6417(.A (n_176), .B (n_175), .Y (n_177));
  NOR2XL g15032__5477(.A (n_173), .B (n_172), .Y (n_174));
  NOR2XL g15031__2398(.A (n_170), .B (n_169), .Y (n_171));
  MXI2XL g15003__5107(.A (n_167), .B (n_166), .S0 (n_190), .Y (n_168));
  CLKINVX1 g15050(.A (n_200), .Y (n_199));
  CLKINVX1 g15052(.A (n_242), .Y (n_198));
  CLKINVX1 g15051(.A (n_249), .Y (n_197));
  CLKINVX1 g15053(.A (n_203), .Y (n_202));
  AOI21X1 g15041__4319(.A0 (n_132), .A1 (n_150), .B0 (n_133), .Y
       (n_164));
  MXI2XL g15040__8428(.A (n_129), .B (n_188), .S0 (n_109), .Y (n_163));
  AOI21X1 g15036__5526(.A0 (n_130), .A1 (n_153), .B0 (n_131), .Y
       (n_162));
  OAI21X1 g15038__6783(.A0 (n_140), .A1 (n_139), .B0 (n_141), .Y
       (n_161));
  AOI21X1 g15035__3680(.A0 (n_135), .A1 (n_134), .B0 (n_136), .Y
       (n_245));
  MXI2XL g15042__1617(.A (n_144), .B (n_146), .S0 (n_160), .Y (n_183));
  MXI2XL g15044__2802(.A (n_151), .B (n_152), .S0 (n_120), .Y (n_175));
  MXI2XL g15045__1705(.A (n_156), .B (n_157), .S0 (n_98), .Y (n_184));
  MXI2XL g15046__5122(.A (n_154), .B (n_155), .S0 (n_159), .Y (n_236));
  CLKINVX1 g15034(.A (n_190), .Y (n_189));
  MXI2XL g15047__8246(.A (n_128), .B (n_160), .S0 (n_158), .Y (n_268));
  MXI2XL g15056__7098(.A (n_157), .B (n_156), .S0 (n_137), .Y (n_180));
  MXI2XL g15057__6131(.A (n_156), .B (n_157), .S0 (cpu_data_in[59]), .Y
       (n_176));
  MXI2XL g15058__1881(.A (n_155), .B (n_154), .S0 (n_166), .Y (n_271));
  MXI2XL g15059__5115(.A (n_154), .B (n_155), .S0 (n_153), .Y (n_169));
  MXI2XL g15062__7482(.A (n_148), .B (n_159), .S0 (n_201), .Y (n_172));
  MXI2XL g15049__4733(.A (n_152), .B (n_151), .S0 (n_150), .Y (n_191));
  AOI22X1 g15063__6161(.A0 (n_154), .A1 (n_151), .B0 (n_155), .B1
       (n_152), .Y (n_213));
  MXI2XL g15064__9315(.A (n_157), .B (n_156), .S0 (n_149), .Y (n_247));
  MXI2XL g15065__9945(.A (n_151), .B (n_152), .S0 (n_108), .Y (n_200));
  MXI2XL g15067__2883(.A (n_159), .B (n_148), .S0 (cpu_data_in[63]), .Y
       (n_242));
  MX2X1 g15068__2346(.A (n_156), .B (n_157), .S0 (n_122), .Y (n_203));
  OAI22X1 g15066__1666(.A0 (n_187), .A1 (n_155), .B0 (n_186), .B1
       (n_154), .Y (n_249));
  OAI22X1 g15054__7410(.A0 (n_146), .A1 (n_145), .B0 (n_144), .B1
       (n_196), .Y (dram_bus_write[19]));
  MXI2XL g15043__6417(.A (n_196), .B (n_145), .S0 (n_87), .Y (n_280));
  MXI2XL g15055__5107(.A (n_95), .B (n_94), .S0 (n_115), .Y (n_194));
  MXI2XL g15060__6260(.A (n_103), .B (n_104), .S0 (n_107), .Y (n_170));
  MXI2XL g15048__4319(.A (n_186), .B (n_187), .S0 (n_159), .Y (n_190));
  NAND2XL g15073__8428(.A (n_140), .B (n_139), .Y (n_141));
  MXI2XL g15061__5526(.A (n_123), .B (n_137), .S0 (n_96), .Y (n_138));
  NOR2XL g15069__6783(.A (n_135), .B (n_134), .Y (n_136));
  NOR2XL g15070__3680(.A (n_132), .B (n_150), .Y (n_133));
  NOR2XL g15071__1617(.A (n_130), .B (n_153), .Y (n_131));
  CLKINVX1 g15075(.A (n_129), .Y (n_188));
  CLKINVX1 g15076(.A (n_151), .Y (n_152));
  CLKINVX1 g15077(.A (n_159), .Y (n_148));
  CLKINVX1 g15092(.A (n_128), .Y (n_160));
  CLKINVX1 g15093(.A (n_156), .Y (n_157));
  CLKINVX1 g15095(.A (n_155), .Y (n_154));
  MXI2XL g15083__2802(.A (n_125), .B (n_105), .S0 (n_106), .Y (n_127));
  MXI2XL g15080__1705(.A (n_117), .B (n_116), .S0 (n_125), .Y (n_126));
  MXI2XL g15078__5122(.A (n_123), .B (n_137), .S0 (n_201), .Y (n_124));
  MXI2XL g15084__8246(.A (n_122), .B (n_121), .S0 (cpu_data_in[60]), .Y
       (n_230));
  MXI2XL g15089__7098(.A (n_166), .B (n_167), .S0 (n_91), .Y (n_129));
  MXI2XL g15086__6131(.A (n_121), .B (n_122), .S0 (n_120), .Y (n_140));
  MXI2XL g15087__1881(.A (n_146), .B (n_144), .S0 (n_125), .Y (n_150));
  MXI2XL g15088__5115(.A (n_146), .B (n_144), .S0 (n_122), .Y (n_153));
  MXI2XL g15085__7482(.A (n_119), .B (n_118), .S0 (n_149), .Y (n_165));
  MXI2XL g15090__4733(.A (n_117), .B (n_116), .S0 (n_113), .Y (n_151));
  MX2X1 g15091__6161(.A (n_112), .B (n_114), .S0 (cpu_data_in[61]), .Y
       (n_159));
  OAI22X1 g15099__9315(.A0 (n_97), .A1 (n_114), .B0 (n_113), .B1
       (n_112), .Y (n_115));
  MXI2XL g15098__9945(.A (n_187), .B (n_186), .S0 (n_110), .Y (n_111));
  MXI2XL g15097__2883(.A (n_117), .B (n_116), .S0 (n_108), .Y (n_109));
  MXI2XL g15082__2346(.A (n_118), .B (n_119), .S0 (n_106), .Y (n_107));
  MXI2XL g15101__1666(.A (n_125), .B (n_105), .S0 (n_99), .Y (n_233));
  OAI22X1 g15102__7410(.A0 (n_114), .A1 (n_117), .B0 (n_112), .B1
       (n_116), .Y (n_139));
  MXI2XL g15103__6417(.A (n_123), .B (n_137), .S0 (n_101), .Y (n_134));
  MXI2XL g15105__5477(.A (n_117), .B (n_116), .S0 (n_102), .Y (n_239));
  OAI22X1 g15106__2398(.A0 (n_104), .A1 (n_123), .B0 (n_103), .B1
       (n_137), .Y (n_128));
  CLKINVX1 g15094(.A (n_196), .Y (n_145));
  OAI22X1 g15107__5107(.A0 (n_102), .A1 (n_118), .B0 (n_101), .B1
       (n_119), .Y (n_156));
  MXI2XL g15109__6260(.A (n_125), .B (n_105), .S0 (n_108), .Y (n_155));
  MXI2XL g15079__4319(.A (n_104), .B (n_103), .S0 (n_99), .Y (n_100));
  MXI2XL g15081__8428(.A (n_113), .B (n_97), .S0 (n_181), .Y (n_98));
  MXI2XL g15096__5526(.A (n_95), .B (n_94), .S0 (n_108), .Y (n_96));
  AOI22X1 g15100__6783(.A0 (n_113), .A1 (n_103), .B0 (n_97), .B1
       (n_104), .Y (n_93));
  MXI2XL g15104__3680(.A (n_102), .B (n_101), .S0 (n_108), .Y (n_130));
  AOI22X1 g15108__1617(.A0 (n_94), .A1 (n_103), .B0 (n_95), .B1
       (n_104), .Y (n_196));
  CLKINVX1 g15175(.A (n_122), .Y (n_121));
  CLKINVX1 g15174(.A (n_114), .Y (n_112));
  CLKINVX1 g15176(.A (n_118), .Y (n_119));
  CLKINVX1 g15177(.A (n_144), .Y (n_146));
  CLKINVX1 g15193(.A (n_166), .Y (n_167));
  CLKINVX1 g15178(.A (n_125), .Y (n_105));
  CLKINVX1 g15194(.A (n_137), .Y (n_123));
  CLKINVX1 g15179(.A (n_116), .Y (n_117));
  CLKINVX1 g15195(.A (n_186), .Y (n_187));
  MXI2XL g15181__2802(.A (n_90), .B (n_91), .S0 (cpu_data_in[57]), .Y
       (n_92));
  MXI2XL g15182__1705(.A (n_90), .B (n_91), .S0 (cpu_data_in[63]), .Y
       (n_181));
  OAI21X1 g15184__5122(.A0 (cpu_data_in[52]), .A1 (n_75), .B0 (n_76),
       .Y (n_114));
  OAI21X1 g15187__8246(.A0 (cpu_data_in[60]), .A1 (n_120), .B0 (n_72),
       .Y (n_144));
  OAI21X1 g15185__7098(.A0 (cpu_data_in[56]), .A1 (n_77), .B0 (n_78),
       .Y (n_122));
  OAI21X1 g15186__6131(.A0 (cpu_data_in[17]), .A1 (n_81), .B0 (n_82),
       .Y (n_118));
  CLKINVX1 g15180(.A (n_104), .Y (n_103));
  MXI2XL g15206__1881(.A (n_88), .B (n_99), .S0 (cpu_data_in[58]), .Y
       (n_186));
  MXI2XL g15205__5115(.A (n_110), .B (n_85), .S0 (cpu_data_in[59]), .Y
       (n_137));
  OAI21X1 g15188__7482(.A0 (cpu_data_in[21]), .A1 (n_73), .B0 (n_74),
       .Y (n_125));
  MXI2XL g15198__4733(.A (n_99), .B (n_88), .S0 (cpu_data_in[57]), .Y
       (n_89));
  MXI2XL g15200__6161(.A (n_84), .B (n_106), .S0 (cpu_data_in[62]), .Y
       (n_87));
  MXI2XL g15201__9315(.A (n_101), .B (n_102), .S0 (cpu_data_in[62]), .Y
       (n_173));
  AOI22X1 g15197__9945(.A0 (n_97), .A1 (n_101), .B0 (n_113), .B1
       (n_102), .Y (n_132));
  MXI2XL g15199__2883(.A (n_110), .B (n_85), .S0 (cpu_data_in[58]), .Y
       (n_178));
  MXI2XL g15196__2346(.A (n_94), .B (n_95), .S0 (cpu_data_in[62]), .Y
       (n_222));
  MXI2XL g15203__1666(.A (n_91), .B (n_90), .S0 (n_149), .Y (n_201));
  MXI2XL g15204__7410(.A (n_95), .B (n_94), .S0 (n_83), .Y (n_166));
  AOI21X1 g15190__6417(.A0 (cpu_data_in[16]), .A1 (n_79), .B0 (n_80),
       .Y (n_108));
  MX2X1 g15189__5477(.A (n_106), .B (n_84), .S0 (cpu_data_in[57]), .Y
       (n_116));
  OAI21X1 g15191__2398(.A0 (cpu_data_in[39]), .A1 (n_69), .B0 (n_70),
       .Y (n_104));
  MXI2XL g15202__5107(.A (cpu_data_in[62]), .B (n_28), .S0 (n_83), .Y
       (n_158));
  NAND2XL g15207__6260(.A (cpu_data_in[17]), .B (n_81), .Y (n_82));
  NOR2XL g15209__4319(.A (cpu_data_in[16]), .B (n_79), .Y (n_80));
  NAND2XL g15210__8428(.A (cpu_data_in[56]), .B (n_77), .Y (n_78));
  NAND2XL g15211__5526(.A (cpu_data_in[52]), .B (n_75), .Y (n_76));
  NAND2XL g15212__6783(.A (cpu_data_in[21]), .B (n_73), .Y (n_74));
  NAND2XL g15213__3680(.A (cpu_data_in[60]), .B (n_120), .Y (n_72));
  SDFFQX1 \bch_fixer_data_out_reg[7] (.CK (clk), .D
       (dram_bus_read[103]), .SI (bch_corrected_data[7]), .SE (n_71),
       .Q (bch_corrected_data[7]));
  SDFFQX1 \bch_fixer_data_out_reg[33] (.CK (clk), .D
       (dram_bus_read[129]), .SI (bch_corrected_data[33]), .SE (n_71),
       .Q (bch_corrected_data[33]));
  SDFFQX1 \bch_fixer_data_out_reg[26] (.CK (clk), .D
       (dram_bus_read[122]), .SI (bch_corrected_data[26]), .SE (n_71),
       .Q (bch_corrected_data[26]));
  SDFFQX1 \bch_fixer_data_out_reg[28] (.CK (clk), .D
       (dram_bus_read[124]), .SI (bch_corrected_data[28]), .SE (n_71),
       .Q (bch_corrected_data[28]));
  SDFFQX1 \bch_fixer_data_out_reg[62] (.CK (clk), .D
       (dram_bus_read[158]), .SI (bch_corrected_data[62]), .SE (n_71),
       .Q (bch_corrected_data[62]));
  SDFFQX1 \bch_fixer_data_out_reg[34] (.CK (clk), .D
       (dram_bus_read[130]), .SI (bch_corrected_data[34]), .SE (n_71),
       .Q (bch_corrected_data[34]));
  SDFFQX1 \bch_fixer_data_out_reg[36] (.CK (clk), .D
       (dram_bus_read[132]), .SI (bch_corrected_data[36]), .SE (n_71),
       .Q (bch_corrected_data[36]));
  SDFFQX1 \bch_fixer_data_out_reg[38] (.CK (clk), .D
       (dram_bus_read[134]), .SI (bch_corrected_data[38]), .SE (n_71),
       .Q (bch_corrected_data[38]));
  SDFFQX1 \bch_fixer_data_out_reg[40] (.CK (clk), .D
       (dram_bus_read[136]), .SI (bch_corrected_data[40]), .SE (n_71),
       .Q (bch_corrected_data[40]));
  SDFFQX1 \bch_fixer_data_out_reg[41] (.CK (clk), .D
       (dram_bus_read[137]), .SI (bch_corrected_data[41]), .SE (n_71),
       .Q (bch_corrected_data[41]));
  SDFFQX1 \bch_fixer_data_out_reg[42] (.CK (clk), .D
       (dram_bus_read[138]), .SI (bch_corrected_data[42]), .SE (n_71),
       .Q (bch_corrected_data[42]));
  SDFFQX1 \bch_fixer_data_out_reg[44] (.CK (clk), .D
       (dram_bus_read[140]), .SI (bch_corrected_data[44]), .SE (n_71),
       .Q (bch_corrected_data[44]));
  SDFFQX1 \bch_fixer_data_out_reg[6] (.CK (clk), .D
       (dram_bus_read[102]), .SI (bch_corrected_data[6]), .SE (n_71),
       .Q (bch_corrected_data[6]));
  SDFFQX1 \bch_fixer_data_out_reg[48] (.CK (clk), .D
       (dram_bus_read[144]), .SI (bch_corrected_data[48]), .SE (n_71),
       .Q (bch_corrected_data[48]));
  SDFFQX1 \bch_fixer_data_out_reg[50] (.CK (clk), .D
       (dram_bus_read[146]), .SI (bch_corrected_data[50]), .SE (n_71),
       .Q (bch_corrected_data[50]));
  SDFFQX1 \bch_fixer_data_out_reg[8] (.CK (clk), .D
       (dram_bus_read[104]), .SI (bch_corrected_data[8]), .SE (n_71),
       .Q (bch_corrected_data[8]));
  SDFFQX1 \bch_fixer_data_out_reg[54] (.CK (clk), .D
       (dram_bus_read[150]), .SI (bch_corrected_data[54]), .SE (n_71),
       .Q (bch_corrected_data[54]));
  SDFFQX1 \bch_fixer_data_out_reg[55] (.CK (clk), .D
       (dram_bus_read[151]), .SI (bch_corrected_data[55]), .SE (n_71),
       .Q (bch_corrected_data[55]));
  SDFFQX1 \bch_fixer_data_out_reg[56] (.CK (clk), .D
       (dram_bus_read[152]), .SI (bch_corrected_data[56]), .SE (n_71),
       .Q (bch_corrected_data[56]));
  SDFFQX1 \bch_fixer_data_out_reg[10] (.CK (clk), .D
       (dram_bus_read[106]), .SI (bch_corrected_data[10]), .SE (n_71),
       .Q (bch_corrected_data[10]));
  SDFFQX1 \bch_fixer_data_out_reg[58] (.CK (clk), .D
       (dram_bus_read[154]), .SI (bch_corrected_data[58]), .SE (n_71),
       .Q (bch_corrected_data[58]));
  SDFFQX1 \bch_fixer_data_out_reg[14] (.CK (clk), .D
       (dram_bus_read[110]), .SI (bch_corrected_data[14]), .SE (n_71),
       .Q (bch_corrected_data[14]));
  SDFFQX1 \bch_fixer_data_out_reg[20] (.CK (clk), .D
       (dram_bus_read[116]), .SI (bch_corrected_data[20]), .SE (n_71),
       .Q (bch_corrected_data[20]));
  SDFFQX1 \bch_fixer_data_out_reg[57] (.CK (clk), .D
       (dram_bus_read[153]), .SI (bch_corrected_data[57]), .SE (n_71),
       .Q (bch_corrected_data[57]));
  SDFFQX1 \bch_fixer_data_out_reg[22] (.CK (clk), .D
       (dram_bus_read[118]), .SI (bch_corrected_data[22]), .SE (n_71),
       .Q (bch_corrected_data[22]));
  SDFFQX1 \bch_fixer_data_out_reg[31] (.CK (clk), .D
       (dram_bus_read[127]), .SI (bch_corrected_data[31]), .SE (n_71),
       .Q (bch_corrected_data[31]));
  SDFFQX1 \bch_fixer_data_out_reg[5] (.CK (clk), .D
       (dram_bus_read[101]), .SI (bch_corrected_data[5]), .SE (n_71),
       .Q (bch_corrected_data[5]));
  SDFFQX1 \bch_fixer_data_out_reg[63] (.CK (clk), .D
       (dram_bus_read[159]), .SI (bch_corrected_data[63]), .SE (n_71),
       .Q (bch_corrected_data[63]));
  SDFFQX1 \bch_fixer_data_out_reg[2] (.CK (clk), .D
       (dram_bus_read[98]), .SI (bch_corrected_data[2]), .SE (n_71), .Q
       (bch_corrected_data[2]));
  SDFFQX1 \bch_fixer_data_out_reg[59] (.CK (clk), .D
       (dram_bus_read[155]), .SI (bch_corrected_data[59]), .SE (n_71),
       .Q (bch_corrected_data[59]));
  SDFFQX1 \bch_fixer_data_out_reg[3] (.CK (clk), .D
       (dram_bus_read[99]), .SI (bch_corrected_data[3]), .SE (n_71), .Q
       (bch_corrected_data[3]));
  SDFFQX1 \bch_fixer_data_out_reg[39] (.CK (clk), .D
       (dram_bus_read[135]), .SI (bch_corrected_data[39]), .SE (n_71),
       .Q (bch_corrected_data[39]));
  SDFFQX1 \bch_fixer_data_out_reg[4] (.CK (clk), .D
       (dram_bus_read[100]), .SI (bch_corrected_data[4]), .SE (n_71),
       .Q (bch_corrected_data[4]));
  SDFFQX1 \bch_fixer_data_out_reg[1] (.CK (clk), .D
       (dram_bus_read[97]), .SI (bch_corrected_data[1]), .SE (n_71), .Q
       (bch_corrected_data[1]));
  SDFFQX1 \bch_fixer_data_out_reg[35] (.CK (clk), .D
       (dram_bus_read[131]), .SI (bch_corrected_data[35]), .SE (n_71),
       .Q (bch_corrected_data[35]));
  SDFFQX1 \bch_fixer_data_out_reg[61] (.CK (clk), .D
       (dram_bus_read[157]), .SI (bch_corrected_data[61]), .SE (n_71),
       .Q (bch_corrected_data[61]));
  SDFFQX1 \bch_fixer_data_out_reg[11] (.CK (clk), .D
       (dram_bus_read[107]), .SI (bch_corrected_data[11]), .SE (n_71),
       .Q (bch_corrected_data[11]));
  SDFFQX1 \bch_fixer_data_out_reg[32] (.CK (clk), .D
       (dram_bus_read[128]), .SI (bch_corrected_data[32]), .SE (n_71),
       .Q (bch_corrected_data[32]));
  SDFFQX1 \bch_fixer_data_out_reg[60] (.CK (clk), .D
       (dram_bus_read[156]), .SI (bch_corrected_data[60]), .SE (n_71),
       .Q (bch_corrected_data[60]));
  SDFFQX1 \bch_fixer_data_out_reg[30] (.CK (clk), .D
       (dram_bus_read[126]), .SI (bch_corrected_data[30]), .SE (n_71),
       .Q (bch_corrected_data[30]));
  SDFFQX1 \bch_fixer_data_out_reg[43] (.CK (clk), .D
       (dram_bus_read[139]), .SI (bch_corrected_data[43]), .SE (n_71),
       .Q (bch_corrected_data[43]));
  SDFFQX1 \bch_fixer_data_out_reg[23] (.CK (clk), .D
       (dram_bus_read[119]), .SI (bch_corrected_data[23]), .SE (n_71),
       .Q (bch_corrected_data[23]));
  SDFFQX1 \bch_fixer_data_out_reg[29] (.CK (clk), .D
       (dram_bus_read[125]), .SI (bch_corrected_data[29]), .SE (n_71),
       .Q (bch_corrected_data[29]));
  SDFFQX1 \bch_fixer_data_out_reg[24] (.CK (clk), .D
       (dram_bus_read[120]), .SI (bch_corrected_data[24]), .SE (n_71),
       .Q (bch_corrected_data[24]));
  SDFFQX1 \bch_fixer_data_out_reg[25] (.CK (clk), .D
       (dram_bus_read[121]), .SI (bch_corrected_data[25]), .SE (n_71),
       .Q (bch_corrected_data[25]));
  SDFFQX1 \bch_fixer_data_out_reg[16] (.CK (clk), .D
       (dram_bus_read[112]), .SI (bch_corrected_data[16]), .SE (n_71),
       .Q (bch_corrected_data[16]));
  SDFFQX1 \bch_fixer_data_out_reg[21] (.CK (clk), .D
       (dram_bus_read[117]), .SI (bch_corrected_data[21]), .SE (n_71),
       .Q (bch_corrected_data[21]));
  SDFFQX1 \bch_fixer_data_out_reg[51] (.CK (clk), .D
       (dram_bus_read[147]), .SI (bch_corrected_data[51]), .SE (n_71),
       .Q (bch_corrected_data[51]));
  SDFFQX1 \bch_fixer_data_out_reg[17] (.CK (clk), .D
       (dram_bus_read[113]), .SI (bch_corrected_data[17]), .SE (n_71),
       .Q (bch_corrected_data[17]));
  SDFFQX1 \bch_fixer_data_out_reg[52] (.CK (clk), .D
       (dram_bus_read[148]), .SI (bch_corrected_data[52]), .SE (n_71),
       .Q (bch_corrected_data[52]));
  SDFFQX1 \bch_fixer_data_out_reg[18] (.CK (clk), .D
       (dram_bus_read[114]), .SI (bch_corrected_data[18]), .SE (n_71),
       .Q (bch_corrected_data[18]));
  SDFFQX1 \bch_fixer_data_out_reg[19] (.CK (clk), .D
       (dram_bus_read[115]), .SI (bch_corrected_data[19]), .SE (n_71),
       .Q (bch_corrected_data[19]));
  SDFFQX1 \bch_fixer_data_out_reg[53] (.CK (clk), .D
       (dram_bus_read[149]), .SI (bch_corrected_data[53]), .SE (n_71),
       .Q (bch_corrected_data[53]));
  SDFFQX1 \bch_fixer_data_out_reg[27] (.CK (clk), .D
       (dram_bus_read[123]), .SI (bch_corrected_data[27]), .SE (n_71),
       .Q (bch_corrected_data[27]));
  SDFFQX1 \bch_fixer_data_out_reg[9] (.CK (clk), .D
       (dram_bus_read[105]), .SI (bch_corrected_data[9]), .SE (n_71),
       .Q (bch_corrected_data[9]));
  SDFFQX1 \bch_fixer_data_out_reg[46] (.CK (clk), .D
       (dram_bus_read[142]), .SI (bch_corrected_data[46]), .SE (n_71),
       .Q (bch_corrected_data[46]));
  SDFFQX1 \bch_fixer_data_out_reg[15] (.CK (clk), .D
       (dram_bus_read[111]), .SI (bch_corrected_data[15]), .SE (n_71),
       .Q (bch_corrected_data[15]));
  SDFFQX1 \bch_fixer_data_out_reg[47] (.CK (clk), .D
       (dram_bus_read[143]), .SI (bch_corrected_data[47]), .SE (n_71),
       .Q (bch_corrected_data[47]));
  SDFFQX1 \bch_fixer_data_out_reg[49] (.CK (clk), .D
       (dram_bus_read[145]), .SI (bch_corrected_data[49]), .SE (n_71),
       .Q (bch_corrected_data[49]));
  SDFFQX1 \bch_fixer_data_out_reg[45] (.CK (clk), .D
       (dram_bus_read[141]), .SI (bch_corrected_data[45]), .SE (n_71),
       .Q (bch_corrected_data[45]));
  SDFFQX1 \bch_fixer_data_out_reg[0] (.CK (clk), .D (n_4), .SI
       (bch_corrected_data[0]), .SE (n_71), .Q (bch_corrected_data[0]));
  SDFFQX1 \bch_fixer_data_out_reg[13] (.CK (clk), .D
       (dram_bus_read[109]), .SI (bch_corrected_data[13]), .SE (n_71),
       .Q (bch_corrected_data[13]));
  SDFFQX1 \bch_fixer_data_out_reg[12] (.CK (clk), .D
       (dram_bus_read[108]), .SI (bch_corrected_data[12]), .SE (n_71),
       .Q (bch_corrected_data[12]));
  SDFFQX1 \bch_fixer_data_out_reg[37] (.CK (clk), .D
       (dram_bus_read[133]), .SI (bch_corrected_data[37]), .SE (n_71),
       .Q (bch_corrected_data[37]));
  NAND2XL g15208__1617(.A (cpu_data_in[39]), .B (n_69), .Y (n_70));
  CLKINVX1 g15256(.A (n_99), .Y (n_88));
  CLKINVX1 g15258(.A (n_106), .Y (n_84));
  CLKINVX1 g15257(.A (n_91), .Y (n_90));
  CLKINVX1 g15259(.A (n_110), .Y (n_85));
  CLKINVX1 g15260(.A (n_113), .Y (n_97));
  CLKINVX1 g15261(.A (n_95), .Y (n_94));
  CLKINVX1 g15262(.A (n_102), .Y (n_101));
  AOI21X1 g15292__2802(.A0 (cpu_data_in[37]), .A1 (n_519), .B0 (n_63),
       .Y (n_73));
  AOI21X1 g15288__1705(.A0 (cpu_data_in[32]), .A1 (n_508), .B0 (n_35),
       .Y (n_79));
  AOI21XL g15289__5122(.A0 (cpu_data_in[24]), .A1 (n_506), .B0 (n_50),
       .Y (n_77));
  AOI21XL g15290__8246(.A0 (cpu_data_in[20]), .A1 (n_510), .B0 (n_55),
       .Y (n_75));
  OAI21X1 g15294__7098(.A0 (cpu_data_in[46]), .A1 (n_511), .B0 (n_57),
       .Y (n_83));
  AOI21XL g15293__6131(.A0 (cpu_data_in[33]), .A1 (n_513), .B0 (n_46),
       .Y (n_81));
  AOI21X1 g15295__1881(.A0 (cpu_data_in[44]), .A1 (n_524), .B0 (n_48),
       .Y (n_120));
  AOI21X1 g15298__5115(.A0 (cpu_data_in[45]), .A1 (n_512), .B0 (n_59),
       .Y (n_149));
  AOI21X1 g15297__7482(.A0 (n_525), .A1 (n_517), .B0 (n_41), .Y (n_91));
  AOI21X1 g15300__4733(.A0 (cpu_data_in[43]), .A1 (n_518), .B0 (n_52),
       .Y (n_110));
  OAI21X1 g15299__6161(.A0 (cpu_data_in[25]), .A1 (n_522), .B0 (n_67),
       .Y (n_106));
  OAI21X1 g15296__9315(.A0 (cpu_data_in[26]), .A1 (n_507), .B0 (n_65),
       .Y (n_99));
  AOI21X1 g15302__9945(.A0 (n_521), .A1 (n_514), .B0 (n_44), .Y (n_95));
  AOI21X1 g15303__2883(.A0 (cpu_data_in[47]), .A1 (n_523), .B0 (n_61),
       .Y (n_102));
  OAI21X1 g15301__2346(.A0 (n_520), .A1 (n_509), .B0 (n_38), .Y
       (n_113));
  AOI21X1 g15291__1666(.A0 (cpu_data_in[55]), .A1 (n_30), .B0 (n_31),
       .Y (n_69));
  DFFRHQX1 \bch_fixer_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_29),
       .Q (bch_fixer_state[0]));
  SDFFRHQX1 \bch_fixer_state_reg[1] (.RN (rst_n), .CK (clk), .D (n_33),
       .SI (bch_fixer_state[1]), .SE (n_32), .Q (bch_fixer_state[1]));
  SDFFRHQX1 \cpu_data_out_reg[40] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[40]), .SI (cpu_data_out[40]), .SE (n_68), .Q
       (cpu_data_out[40]));
  SDFFRHQX1 \cpu_data_out_reg[2] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[2]), .SI (cpu_data_out[2]), .SE (n_68), .Q
       (cpu_data_out[2]));
  SDFFRHQX1 \cpu_data_out_reg[4] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[4]), .SI (cpu_data_out[4]), .SE (n_68), .Q
       (cpu_data_out[4]));
  SDFFRHQX1 \cpu_data_out_reg[11] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[11]), .SI (cpu_data_out[11]), .SE (n_68), .Q
       (cpu_data_out[11]));
  SDFFRHQX1 \cpu_data_out_reg[15] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[15]), .SI (cpu_data_out[15]), .SE (n_68), .Q
       (cpu_data_out[15]));
  SDFFRHQX1 \cpu_data_out_reg[18] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[18]), .SI (cpu_data_out[18]), .SE (n_68), .Q
       (cpu_data_out[18]));
  SDFFRHQX1 \cpu_data_out_reg[20] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[20]), .SI (cpu_data_out[20]), .SE (n_68), .Q
       (cpu_data_out[20]));
  SDFFRHQX1 \cpu_data_out_reg[22] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[22]), .SI (cpu_data_out[22]), .SE (n_68), .Q
       (cpu_data_out[22]));
  SDFFRHQX1 \cpu_data_out_reg[24] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[24]), .SI (cpu_data_out[24]), .SE (n_68), .Q
       (cpu_data_out[24]));
  SDFFRHQX1 \cpu_data_out_reg[26] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[26]), .SI (cpu_data_out[26]), .SE (n_68), .Q
       (cpu_data_out[26]));
  SDFFRHQX1 \cpu_data_out_reg[28] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[28]), .SI (cpu_data_out[28]), .SE (n_68), .Q
       (cpu_data_out[28]));
  SDFFRHQX1 \cpu_data_out_reg[30] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[30]), .SI (cpu_data_out[30]), .SE (n_68), .Q
       (cpu_data_out[30]));
  SDFFRHQX1 \cpu_data_out_reg[32] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[32]), .SI (cpu_data_out[32]), .SE (n_68), .Q
       (cpu_data_out[32]));
  SDFFRHQX1 \cpu_data_out_reg[34] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[34]), .SI (cpu_data_out[34]), .SE (n_68), .Q
       (cpu_data_out[34]));
  SDFFRHQX1 \cpu_data_out_reg[35] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[35]), .SI (cpu_data_out[35]), .SE (n_68), .Q
       (cpu_data_out[35]));
  SDFFRHQX1 \cpu_data_out_reg[37] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[37]), .SI (cpu_data_out[37]), .SE (n_68), .Q
       (cpu_data_out[37]));
  SDFFRHQX1 \cpu_data_out_reg[58] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[58]), .SI (cpu_data_out[58]), .SE (n_68), .Q
       (cpu_data_out[58]));
  SDFFRHQX1 \cpu_data_out_reg[44] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[44]), .SI (cpu_data_out[44]), .SE (n_68), .Q
       (cpu_data_out[44]));
  SDFFRHQX1 \cpu_data_out_reg[46] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[46]), .SI (cpu_data_out[46]), .SE (n_68), .Q
       (cpu_data_out[46]));
  SDFFRHQX1 \cpu_data_out_reg[48] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[48]), .SI (cpu_data_out[48]), .SE (n_68), .Q
       (cpu_data_out[48]));
  SDFFRHQX1 \cpu_data_out_reg[50] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[50]), .SI (cpu_data_out[50]), .SE (n_68), .Q
       (cpu_data_out[50]));
  SDFFRHQX1 \cpu_data_out_reg[51] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[51]), .SI (cpu_data_out[51]), .SE (n_68), .Q
       (cpu_data_out[51]));
  SDFFRHQX1 \cpu_data_out_reg[52] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[52]), .SI (cpu_data_out[52]), .SE (n_68), .Q
       (cpu_data_out[52]));
  SDFFRHQX1 \cpu_data_out_reg[54] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[54]), .SI (cpu_data_out[54]), .SE (n_68), .Q
       (cpu_data_out[54]));
  SDFFRHQX1 \cpu_data_out_reg[56] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[56]), .SI (cpu_data_out[56]), .SE (n_68), .Q
       (cpu_data_out[56]));
  SDFFRHQX1 \cpu_data_out_reg[5] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[5]), .SI (cpu_data_out[5]), .SE (n_68), .Q
       (cpu_data_out[5]));
  SDFFRHQX1 \cpu_data_out_reg[42] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[42]), .SI (cpu_data_out[42]), .SE (n_68), .Q
       (cpu_data_out[42]));
  SDFFRHQX1 \cpu_data_out_reg[59] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[59]), .SI (cpu_data_out[59]), .SE (n_68), .Q
       (cpu_data_out[59]));
  SDFFRHQX1 \cpu_data_out_reg[38] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[38]), .SI (cpu_data_out[38]), .SE (n_68), .Q
       (cpu_data_out[38]));
  SDFFRHQX1 \cpu_data_out_reg[61] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[61]), .SI (cpu_data_out[61]), .SE (n_68), .Q
       (cpu_data_out[61]));
  SDFFRHQX1 \cpu_data_out_reg[63] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[63]), .SI (cpu_data_out[63]), .SE (n_68), .Q
       (cpu_data_out[63]));
  SDFFRHQX1 \cpu_data_out_reg[41] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[41]), .SI (cpu_data_out[41]), .SE (n_68), .Q
       (cpu_data_out[41]));
  SDFFRHQX1 \cpu_data_out_reg[19] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[19]), .SI (cpu_data_out[19]), .SE (n_68), .Q
       (cpu_data_out[19]));
  SDFFRHQX1 \cpu_data_out_reg[16] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[16]), .SI (cpu_data_out[16]), .SE (n_68), .Q
       (cpu_data_out[16]));
  SDFFRHQX1 \cpu_data_out_reg[21] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[21]), .SI (cpu_data_out[21]), .SE (n_68), .Q
       (cpu_data_out[21]));
  SDFFRHQX1 \cpu_data_out_reg[55] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[55]), .SI (cpu_data_out[55]), .SE (n_68), .Q
       (cpu_data_out[55]));
  SDFFRHQX1 \cpu_data_out_reg[10] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[10]), .SI (cpu_data_out[10]), .SE (n_68), .Q
       (cpu_data_out[10]));
  SDFFRHQX1 \cpu_data_out_reg[57] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[57]), .SI (cpu_data_out[57]), .SE (n_68), .Q
       (cpu_data_out[57]));
  SDFFRHQX1 \cpu_data_out_reg[47] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[47]), .SI (cpu_data_out[47]), .SE (n_68), .Q
       (cpu_data_out[47]));
  SDFFRHQX1 \cpu_data_out_reg[53] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[53]), .SI (cpu_data_out[53]), .SE (n_68), .Q
       (cpu_data_out[53]));
  SDFFRHQX1 \cpu_data_out_reg[17] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[17]), .SI (cpu_data_out[17]), .SE (n_68), .Q
       (cpu_data_out[17]));
  NAND2XL g15321__7410(.A (cpu_data_in[25]), .B (n_522), .Y (n_67));
  NAND2XL g15306__6417(.A (cpu_data_in[26]), .B (n_507), .Y (n_65));
  NOR2XL g15308__5477(.A (cpu_data_in[37]), .B (n_519), .Y (n_63));
  NOR2XL g15309__2398(.A (cpu_data_in[47]), .B (n_523), .Y (n_61));
  NOR2XL g15310__5107(.A (cpu_data_in[45]), .B (n_512), .Y (n_59));
  NAND2XL g15311__6260(.A (cpu_data_in[46]), .B (n_511), .Y (n_57));
  NOR2XL g15312__4319(.A (cpu_data_in[20]), .B (n_510), .Y (n_55));
  AO22XL g15313__8428(.A0 (bch_fixer_state[2]), .A1 (n_24), .B0
       (bch_fixer_state[0]), .B1 (bch_fixer_state[1]), .Y (n_53));
  NOR2XL g15314__5526(.A (cpu_data_in[43]), .B (n_518), .Y (n_52));
  NOR2XL g15315__6783(.A (cpu_data_in[24]), .B (n_506), .Y (n_50));
  NOR2XL g15316__3680(.A (cpu_data_in[44]), .B (n_524), .Y (n_48));
  NOR2XL g15317__1617(.A (cpu_data_in[33]), .B (n_513), .Y (n_46));
  NOR2XL g15318__2802(.A (n_521), .B (n_514), .Y (n_44));
  NOR2XL g15319__1705(.A (n_525), .B (n_517), .Y (n_41));
  NAND2XL g15320__5122(.A (n_520), .B (n_509), .Y (n_38));
  NOR2XL g15305__8246(.A (cpu_data_in[32]), .B (n_508), .Y (n_35));
  SDFFRHQX1 \cpu_data_out_reg[33] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[33]), .SI (cpu_data_out[33]), .SE (n_68), .Q
       (cpu_data_out[33]));
  SDFFRHQX1 \cpu_data_out_reg[7] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[7]), .SI (cpu_data_out[7]), .SE (n_68), .Q
       (cpu_data_out[7]));
  SDFFRHQX1 \cpu_data_out_reg[6] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[6]), .SI (cpu_data_out[6]), .SE (n_68), .Q
       (cpu_data_out[6]));
  SDFFRHQX1 \cpu_data_out_reg[1] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[1]), .SI (cpu_data_out[1]), .SE (n_68), .Q
       (cpu_data_out[1]));
  SDFFRHQX1 \cpu_data_out_reg[49] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[49]), .SI (cpu_data_out[49]), .SE (n_68), .Q
       (cpu_data_out[49]));
  SDFFRHQX1 \cpu_data_out_reg[45] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[45]), .SI (cpu_data_out[45]), .SE (n_68), .Q
       (cpu_data_out[45]));
  SDFFRHQX1 \cpu_data_out_reg[14] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[14]), .SI (cpu_data_out[14]), .SE (n_68), .Q
       (cpu_data_out[14]));
  SDFFRHQX1 \cpu_data_out_reg[12] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[12]), .SI (cpu_data_out[12]), .SE (n_68), .Q
       (cpu_data_out[12]));
  SDFFRHQX1 \cpu_data_out_reg[3] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[3]), .SI (cpu_data_out[3]), .SE (n_68), .Q
       (cpu_data_out[3]));
  SDFFRHQX1 \cpu_data_out_reg[13] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[13]), .SI (cpu_data_out[13]), .SE (n_68), .Q
       (cpu_data_out[13]));
  SDFFRHQX1 \cpu_data_out_reg[9] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[9]), .SI (cpu_data_out[9]), .SE (n_68), .Q
       (cpu_data_out[9]));
  SDFFRHQX1 \cpu_data_out_reg[39] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[39]), .SI (cpu_data_out[39]), .SE (n_68), .Q
       (cpu_data_out[39]));
  SDFFRHQX1 \cpu_data_out_reg[8] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[8]), .SI (cpu_data_out[8]), .SE (n_68), .Q
       (cpu_data_out[8]));
  SDFFRHQX1 \cpu_data_out_reg[0] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[0]), .SI (cpu_data_out[0]), .SE (n_68), .Q
       (cpu_data_out[0]));
  SDFFRHQX1 \cpu_data_out_reg[36] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[36]), .SI (cpu_data_out[36]), .SE (n_68), .Q
       (cpu_data_out[36]));
  SDFFRHQX1 \cpu_data_out_reg[27] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[27]), .SI (cpu_data_out[27]), .SE (n_68), .Q
       (cpu_data_out[27]));
  SDFFRHQX1 \cpu_data_out_reg[60] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[60]), .SI (cpu_data_out[60]), .SE (n_68), .Q
       (cpu_data_out[60]));
  SDFFRHQX1 \cpu_data_out_reg[31] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[31]), .SI (cpu_data_out[31]), .SE (n_68), .Q
       (cpu_data_out[31]));
  SDFFRHQX1 \cpu_data_out_reg[29] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[29]), .SI (cpu_data_out[29]), .SE (n_68), .Q
       (cpu_data_out[29]));
  SDFFRHQX1 \cpu_data_out_reg[23] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[23]), .SI (cpu_data_out[23]), .SE (n_68), .Q
       (cpu_data_out[23]));
  SDFFRHQX1 bch_fixer_done_reg(.RN (rst_n), .CK (clk), .D (bch_done),
       .SI (bch_fixer_state[2]), .SE (n_23), .Q (bch_done));
  SDFFRHQX1 \cpu_data_out_reg[25] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[25]), .SI (cpu_data_out[25]), .SE (n_68), .Q
       (cpu_data_out[25]));
  SDFFRHQX1 \cpu_data_out_reg[43] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[43]), .SI (cpu_data_out[43]), .SE (n_68), .Q
       (cpu_data_out[43]));
  SDFFRHQX1 \cpu_data_out_reg[62] (.RN (rst_n), .CK (clk), .D
       (bch_corrected_data[62]), .SI (cpu_data_out[62]), .SE (n_68), .Q
       (cpu_data_out[62]));
  OR3X2 g15304__7098(.A (n_15), .B (n_33), .C (n_32), .Y (n_71));
  NOR2XL g15307__6131(.A (cpu_data_in[55]), .B (n_30), .Y (n_31));
  OA21XL g15322__1881(.A0 (bch_fixer_state[0]), .A1 (n_25), .B0 (n_32),
       .Y (n_29));
  DFFRHQX1 data_ready_reg(.RN (rst_n), .CK (clk), .D (n_22), .Q
       (data_ready));
  MXI2XL g15324__5115(.A (cpu_data_in[62]), .B (n_28), .S0
       (cpu_data_in[63]), .Y (n_135));
  XNOR2XL g15342__2802(.A (cpu_data_in[7]), .B (cpu_data_in[23]), .Y
       (n_30));
  NAND2XL g15346__1705(.A (bch_fixer_state[0]), .B (n_25), .Y (n_32));
  INVXL g15347(.A (n_23), .Y (n_24));
  INVXL g15348(.A (n_68), .Y (n_22));
  NOR2XL g15349__5122(.A (bch_fixer_state[0]), .B (bch_fixer_state[1]),
       .Y (n_23));
  NAND2X4 g15350__8246(.A (read_en), .B (bch_done), .Y (n_68));
  INVXL g15375(.A (rst_n), .Y (n_15));
  CLKINVX1 g15365(.A (cpu_data_in[62]), .Y (n_28));
  CLKINVX1 g15351(.A (dram_bus_read[96]), .Y (n_4));
  CLKINVX1 g15362(.A (bch_fixer_state[1]), .Y (n_33));
  XNOR2X1 g2(.A (n_140), .B (n_165), .Y (n_504));
  XNOR2XL g15509(.A (n_158), .B (n_126), .Y (n_505));
  XNOR2XL g15510(.A (cpu_data_in[40]), .B (cpu_data_in[8]), .Y (n_506));
  XNOR2XL g15511(.A (cpu_data_in[42]), .B (cpu_data_in[10]), .Y
       (n_507));
  XNOR2X1 g15512(.A (cpu_data_in[48]), .B (cpu_data_in[0]), .Y (n_508));
  XNOR2XL g15513(.A (cpu_data_in[35]), .B (cpu_data_in[19]), .Y
       (n_509));
  XNOR2XL g15514(.A (cpu_data_in[36]), .B (cpu_data_in[4]), .Y (n_510));
  XNOR2XL g15515(.A (cpu_data_in[30]), .B (cpu_data_in[14]), .Y
       (n_511));
  XNOR2X1 g15516(.A (cpu_data_in[29]), .B (cpu_data_in[13]), .Y
       (n_512));
  XNOR2XL g15517(.A (cpu_data_in[49]), .B (cpu_data_in[1]), .Y (n_513));
  XNOR2X1 g15518(.A (cpu_data_in[18]), .B (cpu_data_in[2]), .Y (n_514));
  XNOR2XL g15519(.A (cpu_data_in[58]), .B (cpu_data_in[61]), .Y
       (n_515));
  XNOR2XL g15520(.A (cpu_data_in[60]), .B (cpu_data_in[59]), .Y
       (n_516));
  XNOR2X1 g15521(.A (cpu_data_in[54]), .B (cpu_data_in[6]), .Y (n_517));
  XNOR2X1 g15522(.A (cpu_data_in[27]), .B (cpu_data_in[11]), .Y
       (n_518));
  XNOR2X1 g15523(.A (cpu_data_in[53]), .B (cpu_data_in[5]), .Y (n_519));
  CLKXOR2X1 g15524(.A (cpu_data_in[51]), .B (cpu_data_in[3]), .Y
       (n_520));
  CLKXOR2X1 g15525(.A (cpu_data_in[50]), .B (cpu_data_in[34]), .Y
       (n_521));
  XNOR2XL g15526(.A (cpu_data_in[41]), .B (cpu_data_in[9]), .Y (n_522));
  XNOR2X1 g15527(.A (cpu_data_in[31]), .B (cpu_data_in[15]), .Y
       (n_523));
  XNOR2X1 g15528(.A (cpu_data_in[28]), .B (cpu_data_in[12]), .Y
       (n_524));
  CLKXOR2X1 g15529(.A (cpu_data_in[38]), .B (cpu_data_in[22]), .Y
       (n_525));
  DFFRX1 \bch_fixer_state_reg[2] (.RN (rst_n), .CK (clk), .D (n_53), .Q
       (bch_fixer_state[2]), .QN (n_25));
endmodule

